name: Release

on:
  push:
    branches:
      - main
      - beta

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write  # Required for OIDC trusted publishing (2025 standard)

jobs:
  release:
    name: Automated Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'  # semantic-release v25+ requires Node 22.14+ (v24.10.0+ for v24 range)

      - name: Install dependencies
        run: npm ci

      - name: Verify dependency signatures
        run: npm audit signatures

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # NPM_TOKEN not needed with OIDC trusted publishing
        run: npm run release
